### ISSUE TITLE
0.1 Roadmap

### ISSUE THREAD

**Issue by Anders429** [Anders429/brood#16]
This crate is getting closer and closer to being ready for a `0.1.0` release, but there are still a few things that need to be done. Ideally, these tasks can be completed in the next couple of months.

### Documentation
- [x] Document public API.
- [ ] Document internal API.
- [x] Ensure every `unsafe` item has a `# Safety` section.
- [x] Ensure every item that can panic has a `# Panic` section.
- [x] License files
- [x] README file
- [ ] Contributions file
- [ ] Architecture overview file. 
- [x] Feature-gated items should be indicated as such in documentation.
- [x] Fill out manifest file completely.

### Tests
- [ ] Unit tests.
- [x] Compilation tests (for macros, using something like `trybuild`).
- [x] Set up CI.

### Organization
- [x] Determine what exactly should be exported at the crate level (including macros).
- [x] Fix redundant naming issue within modules (e.g. `registry::NullRegistry` vs `registry::Null`).
- [x] Reorganize the `query` module.

### Code Health
- [x] High code coverage.
- [x] Establish lints to be run within `cargo check` and `cargo clippy`
    - Possibly include `clippy::pedantic`.
- [x] Check `clippy` lints on CI.

### Safety
- [x] Audit all `unsafe` blocks, annotating why they are sound with a `SAFETY` comment.

### Stability
- [x] Ensure compiles on a `stable` channel of Rust.
    - This won't be possible until the next stable release, `1.58.0`. However, this release should come in, like, the next week.
- [x] Test for MSRV on CI.

**Comment by Anders429** [comment]
All public APIs are tested and documented. There could be a bit more test coverage, but we are sitting at 95+%, which is pretty good. Everything is done except for the private API documentation and more unit tests for private internal APIs (which are touched by the public APIs, but it would be good to ensure everything internally is doing what is expected).

I haven't completed an ARCHITECTURE.md or CONTRIBUTING.md file, which I intended to do, but I can do those later. They're not exactly necessary at the moment.

With that said, I think it's time to publish a 0.1.0 version.
