### ISSUE TITLE
Unit testing tracking issue

### ISSUE THREAD

**Issue by Anders429** [Anders429/brood#71]
This is a tracking issue for complete unit testing of the code base. As modules have unit tests written for them, they will be checked off the following list.

- [ ] archetype
  - [ ] identifier
    - [ ] impl_serde.rs
    - [ ] iter.rs
    - [ ] mod.rs
  - [ ] impl_debug.rs
  - [ ] impl_drop.rs
  - [ ] impl_eq.rs
  - [ ] impl_send.rs
  - [ ] impl_serde.rs
  - [ ] mod.rs
- [ ] archetypes
  - [ ] impl_debug.rs
  - [ ] impl_eq.rs
  - [ ] impl_serde.rs
  - [ ] iter.rs
  - [ ] mod.rs
  - [ ] par_iter.rs
- [ ] entities
  - [ ] seal
    - [ ] length.rs
    - [ ] mod.rs
    - [ ] storage.rs
  - [ ] mod.rs
- [ ] entity
  - [ ] allocator
    - [ ] impl_serde.rs
    - [ ] location.rs
    - [ ] locations.rs
    - [ ] mod.rs
    - [ ] slot.rs
  - [ ] identifier
    - [ ] impl_serde.rs
    - [ ] mod.rs
  - [ ] seal
    - [ ] mod.rs
    - [ ] storage.rs
  - [ ] mod.rs
- [ ] query
  - [ ] filter
    - [ ] mod.rs
    - [ ] seal.rs
  - [ ] result
    - [ ] iter.rs
    - [ ] mod.rs
    - [ ] par_iter.rs
  - [ ] view
    - [ ] par
      - [ ] seal
        - [ ] mod.rs
        - [ ] repeat.rs
      - [ ] mod.rs
    - [ ] assertion_buffer.rs
    - [ ] mod.rs
    - [ ] seal.rs
  - [ ] claim.rs
  - [ ] mod.rs
- [ ] registry
  - [ ] seal
    - [ ] assertions.rs
    - [ ] length.rs
    - [ ] mod.rs
    - [ ] storage.rs
  - [ ] debug.rs
  - [ ] eq.rs
  - [ ] mod.rs
  - [ ] send.rs
  - [ ] serde.rs
  - [ ] sync.rs
- [ ] system
  - [ ] schedule
    - [ ] raw_task
      - [ ] mod.rs
      - [ ] seal.rs
    - [ ] stage
      - [ ] mod.rs
      - [ ] seal.rs
    - [ ] builder.rs
    - [ ] mod.rs
    - [ ] sendable.rs
    - [ ] task.rs
  - [ ] mod.rs
  - [ ] null.rs
  - [ ] par.rs
- [ ] world
  - [ ] entry.rs
  - [ ] impl_debug.rs
  - [ ] impl_default.rs
  - [ ] impl_eq.rs
  - [ ] impl_send.rs
  - [ ] impl_serde.rs
  - [ ] impl_sync.rs
  - [ ] mod.rs
- [ ] component.rs
- [ ] doc.rs
- [ ] hlist.rs
- [ ] lib.rs
- [ ] macro.rs
- [ ] reexports.rs

From this point forward, all pull requests should include unit tests for everything added. This wasn't included in the past due to the experimental nature of things, but now that this is shaping into a real library tests need to be included from the get-go.
