### ISSUE TITLE
Full Documentation tracking issue

### ISSUE THREAD

**Issue by Anders429** [Anders429/brood#72]
Tracking issue for fully documenting all items in the library.

"All items" includes everything, both public and private. Up to this point, everything that is public has been documented. However, private items are not documented. This issue essentially just tracks this private item documentation.

Note that private item documentation is a goal because it makes maintainability and extensibility of the library that much easier.

As modules are completely documented, they should be checked off below:

- [ ] archetype
  - [ ] identifier
    - [ ] impl_serde.rs
    - [ ] iter.rs
    - [ ] mod.rs
  - [ ] impl_debug.rs
  - [ ] impl_drop.rs
  - [ ] impl_eq.rs
  - [ ] impl_send.rs
  - [ ] impl_serde.rs
  - [ ] mod.rs
- [ ] archetypes
  - [ ] impl_debug.rs
  - [ ] impl_eq.rs
  - [ ] impl_serde.rs
  - [ ] iter.rs
  - [ ] mod.rs
  - [ ] par_iter.rs
- [ ] entities
  - [ ] seal
    - [ ] length.rs
    - [ ] mod.rs
    - [ ] storage.rs
  - [ ] mod.rs
- [ ] entity
  - [ ] allocator
    - [ ] impl_serde.rs
    - [ ] location.rs
    - [ ] locations.rs
    - [ ] mod.rs
    - [ ] slot.rs
  - [ ] identifier
    - [ ] impl_serde.rs
    - [ ] mod.rs
  - [ ] seal
    - [ ] mod.rs
    - [ ] storage.rs
  - [ ] mod.rs
- [ ] query
  - [ ] filter
    - [ ] mod.rs
    - [ ] seal.rs
  - [ ] result
    - [ ] iter.rs
    - [ ] mod.rs
    - [ ] par_iter.rs
  - [ ] view
    - [ ] par
      - [ ] seal
        - [ ] mod.rs
        - [ ] repeat.rs
      - [ ] mod.rs
    - [ ] assertion_buffer.rs
    - [ ] mod.rs
    - [ ] seal.rs
  - [ ] claim.rs
  - [ ] mod.rs
- [ ] registry
  - [ ] seal
    - [ ] assertions.rs
    - [ ] length.rs
    - [ ] mod.rs
    - [ ] storage.rs
  - [ ] debug.rs
  - [ ] eq.rs
  - [ ] mod.rs
  - [ ] send.rs
  - [ ] serde.rs
  - [ ] sync.rs
- [ ] system
  - [ ] schedule
    - [ ] raw_task
      - [ ] mod.rs
      - [ ] seal.rs
    - [ ] stage
      - [ ] mod.rs
      - [ ] seal.rs
    - [ ] builder.rs
    - [ ] mod.rs
    - [ ] sendable.rs
    - [ ] task.rs
  - [ ] mod.rs
  - [ ] null.rs
  - [ ] par.rs
- [ ] world
  - [ ] entry.rs
  - [ ] impl_debug.rs
  - [ ] impl_default.rs
  - [ ] impl_eq.rs
  - [ ] impl_send.rs
  - [ ] impl_serde.rs
  - [ ] impl_sync.rs
  - [ ] mod.rs
- [ ] component.rs
- [ ] doc.rs
- [ ] hlist.rs
- [ ] lib.rs
- [ ] macro.rs
- [ ] reexports.rs
